#!/bin/bash
repo_name="localrepo"
master_url="https://raw.githubusercontent.com/lee8oi/march/master/"
packages_i686=""
packages_x86_64=""
packages_both="\
tmux
vim
elinks
vim-syntastic
zsh
zsh-completions
zsh-syntax-highlighting
"
create_repo() {
	if [ $1 ]; then
		mkdir -p $1
		if [ -d $1 ]; then
			repo_arch=`basename $1`
			full_path=`cd $1 ; pwd`
			repo_conf=${full_path}/${repo_name}.conf
			db_dir=${full_path}/${repo_arch}_db
			conf_file=${full_path}/pacman.${repo_arch}.conf
			wget -P $full_path ${master_url}/pacman.${repo_arch}.conf
			if [ $? -ne 0 ]; then
				echo "Config download failed!"
				echo "Invalid architecture '${repo_arch}' or broken master url"
				exit 1
			fi
			mkdir $db_dir &&
			mkdir ${full_path}/package_lists
			if [ ! -f  $repo_conf ]; then
				touch $repo_conf
				#echo "db_dir=${full_path}/${1}_db" >> $repo_conf
				echo "pac_opts=\"--noconfirm --config $conf_file --dbpath $db_dir --cachedir $full_path\"" >> $repo_conf
			fi
		fi
	fi
}

fetch_packages () {
	if [ $USER != "root" ]; then
		echo "march update requires root privileges!"
		exit 1
	fi
	if [ $1 ];  then
		if [ -f $1/${repo_name}.conf ]; then
			repo_arch=`basename $1`
			pacman -Syu
			pack_name=$"packages_${repo_arch}"
			eval pkgs="\$$pack_name"
			source $1/${repo_name}.conf

			pacman $pac_opts -Syy
			pacman $pac_opts -Sw $pkgs $packages_both
		else
			echo "Invalid repo: $1"
		fi
	else
		echo "Example usage: $0 fetch i686"
	fi
}

update_repo() {
	if [ $1 ] && [ -d $1 ]; then
		repo-add $1/${repo_name}.db.tar.gz $1/*.pkg.tar.xz
		exit 0
	else
		echo "Example usage: $0 update ./i686"
		exit 1
	fi
}

# repo_add() {
# 	if [ -d $1 ]; then
# 		repo-add $1/${repo_name}.db.tar.gz $1/*.pkg.tar.xz
# 	else
# 		echo "Package directory not found: \"$1\""
# 		exit 1
# 	fi
# }

download_lists() {
	if [ -d $1 ]; then
		for i in ${@:2}; do
			wget -P $1 ${master_url}/package_lists/$i.list
			if [ $? -ne 0 ];then
				exit 1
			fi
		done
	else
		echo "Invalid repo '$1'"
	fi
}

remove_lists() {
	if [ -d $1/package_lists ]; then
		for i in ${@:2}; do
			rm $1/package_lists/$i.list
		done
	fi
}

package_list() {
	help () {
		echo "Usage: $0 list <add|remove> <repo> <list(s)> "
		echo "Example: $0 list add ~/localrepo/i686 base"
	}
	if [ $# -ge 3 ]; then 
		case "$1" in
			add)
				download_lists $2/package_lists ${@:3}
				;;
			remove)
				remove_lists ${@:2}
				;;
			*)
				help
				;;
		esac
	else
		help
	fi
}

package_repo() {
	help () {
		echo "Usage: $0 repo <create|update> <repo path>"
		echo "Example: $0 repo create ~/localrepo/i686"
	}
	if [ $# -ge 2 ]; then 
		case "$1" in
			create)
				create_repo $2
				;;
			update)
				fetch_packages $2 &&
				update_repo $2
				;;
			*)
				help
				;;
		esac
	else
		help
	fi

}

case "$1" in
	list) 
		package_list ${@:2}
		;;
	repo) 
		package_repo ${@:2}
		;;
esac
